version: '3'
services:
    proxy:
        image: nginx:latest
        container_name: proxy    
        ports:
            - "3001:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        restart: "unless-stopped"
    express:
        build:
            context: ./
        ports:
            - "3000:3000"
        expose:
            - "3306"
