version: '3'
services:
    proxy:
        image: nginx:latest
        container_name: proxy    
        ports:
            - "3000:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        restart: "unless-stopped"
    express1:
        build:
            context: ./
            #expose:
            #- "3306"
    express2:
        build:
            context: ./
            #expose:
            #- "3306"
