version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: proxy    
        ports:
            - "3000:3000"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        restart: "unless-stopped"
    express1:
        build:
            context: ./
        ports:
            - "3001:3000"
        expose:
            - "3306"
    express2:
        build:
            context: ./
        ports:
            - "3002:3000"
        expose:
            - "3306"
